[2025-03-13T20:31:36.531+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-13T20:31:36.578+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.test_validating_data_silver_layer.crm_salse_details scheduled__2025-03-13T20:15:00+00:00 [queued]>
[2025-03-13T20:31:36.601+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.test_validating_data_silver_layer.crm_salse_details scheduled__2025-03-13T20:15:00+00:00 [queued]>
[2025-03-13T20:31:36.602+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-13T20:31:36.627+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): test_validating_data_silver_layer.crm_salse_details> on 2025-03-13 20:15:00+00:00
[2025-03-13T20:31:36.645+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1122) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T20:31:36.647+0000] {standard_task_runner.py:63} INFO - Started process 1132 to run task
[2025-03-13T20:31:36.650+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'test_validating_data_silver_layer.crm_salse_details', 'scheduled__2025-03-13T20:15:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpqirpkoes']
[2025-03-13T20:31:36.657+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask test_validating_data_silver_layer.crm_salse_details
[2025-03-13T20:31:36.768+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.test_validating_data_silver_layer.crm_salse_details scheduled__2025-03-13T20:15:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-13T20:31:36.943+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='test_validating_data_silver_layer.crm_salse_details' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T20:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T20:15:00+00:00'
[2025-03-13T20:31:36.946+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-13T20:31:36.969+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-13T20:31:36.969+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --full-refresh --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/sales --models crm_salse_details']
[2025-03-13T20:31:37.000+0000] {subprocess.py:86} INFO - Output:
[2025-03-13T20:31:42.424+0000] {subprocess.py:93} INFO - [0m20:31:42  Running with dbt=1.9.3
[2025-03-13T20:31:43.527+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (19.0.1), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-03-13T20:31:43.528+0000] {subprocess.py:93} INFO -   warn_incompatible_dep(
[2025-03-13T20:31:44.468+0000] {subprocess.py:93} INFO - [0m20:31:44  Registered adapter: snowflake=1.9.2
[2025-03-13T20:31:45.301+0000] {subprocess.py:93} INFO - [0m20:31:45  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-13T20:31:45.302+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-13T20:31:45.303+0000] {subprocess.py:93} INFO - - models.sales.Gold_layer
[2025-03-13T20:31:45.693+0000] {subprocess.py:93} INFO - [0m20:31:45  Found 6 models, 35 data tests, 6 sources, 855 macros
[2025-03-13T20:31:45.696+0000] {subprocess.py:93} INFO - [0m20:31:45
[2025-03-13T20:31:45.697+0000] {subprocess.py:93} INFO - [0m20:31:45  Concurrency: 2 threads (target='dev')
[2025-03-13T20:31:45.697+0000] {subprocess.py:93} INFO - [0m20:31:45
[2025-03-13T20:31:46.662+0000] {subprocess.py:93} INFO - [0m20:31:46  1 of 1 START sql incremental model layer_silver.crm_salse_details .............. [RUN]
[2025-03-13T20:31:47.904+0000] {subprocess.py:93} INFO - [0m20:31:47  1 of 1 OK created sql incremental model layer_silver.crm_salse_details ......... [[32mSUCCESS 1[0m in 1.24s]
[2025-03-13T20:31:48.143+0000] {subprocess.py:93} INFO - [0m20:31:48
[2025-03-13T20:31:48.144+0000] {subprocess.py:93} INFO - [0m20:31:48  Finished running 1 incremental model in 0 hours 0 minutes and 2.44 seconds (2.44s).
[2025-03-13T20:31:48.226+0000] {subprocess.py:93} INFO - [0m20:31:48
[2025-03-13T20:31:48.226+0000] {subprocess.py:93} INFO - [0m20:31:48  [32mCompleted successfully[0m
[2025-03-13T20:31:48.227+0000] {subprocess.py:93} INFO - [0m20:31:48
[2025-03-13T20:31:48.228+0000] {subprocess.py:93} INFO - [0m20:31:48  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-03-13T20:31:49.665+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-13T20:31:49.666+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-13T20:31:49.692+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=test_validating_data_silver_layer.crm_salse_details, execution_date=20250313T201500, start_date=20250313T203136, end_date=20250313T203149
[2025-03-13T20:31:49.740+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-13T20:31:49.759+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T20:31:49.760+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
