[2025-03-13T20:06:03.644+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-13T20:06:03.699+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.silver_layer.crm_cust_info scheduled__2025-03-13T19:45:00+00:00 [queued]>
[2025-03-13T20:06:03.716+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.silver_layer.crm_cust_info scheduled__2025-03-13T19:45:00+00:00 [queued]>
[2025-03-13T20:06:03.716+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-13T20:06:03.745+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): silver_layer.crm_cust_info> on 2025-03-13 19:45:00+00:00
[2025-03-13T20:06:03.758+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=442) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T20:06:03.761+0000] {standard_task_runner.py:63} INFO - Started process 454 to run task
[2025-03-13T20:06:03.761+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'silver_layer.crm_cust_info', 'scheduled__2025-03-13T19:45:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp19pj0nz4']
[2025-03-13T20:06:03.767+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask silver_layer.crm_cust_info
[2025-03-13T20:06:03.855+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.silver_layer.crm_cust_info scheduled__2025-03-13T19:45:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-13T20:06:04.067+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='silver_layer.crm_cust_info' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T19:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T19:45:00+00:00'
[2025-03-13T20:06:04.068+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-13T20:06:04.093+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-13T20:06:04.094+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --full-refresh --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/sales --models crm_cust_info']
[2025-03-13T20:06:04.118+0000] {subprocess.py:86} INFO - Output:
[2025-03-13T20:06:09.254+0000] {subprocess.py:93} INFO - [0m20:06:09  Running with dbt=1.9.3
[2025-03-13T20:06:10.770+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (19.0.1), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-03-13T20:06:10.770+0000] {subprocess.py:93} INFO -   warn_incompatible_dep(
[2025-03-13T20:06:11.834+0000] {subprocess.py:93} INFO - [0m20:06:11  Registered adapter: snowflake=1.9.2
[2025-03-13T20:06:13.177+0000] {subprocess.py:93} INFO - [0m20:06:13  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-13T20:06:13.177+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-13T20:06:13.178+0000] {subprocess.py:93} INFO - - models.sales.Gold_layer
[2025-03-13T20:06:13.611+0000] {subprocess.py:93} INFO - [0m20:06:13  Found 6 models, 35 data tests, 6 sources, 855 macros
[2025-03-13T20:06:13.615+0000] {subprocess.py:93} INFO - [0m20:06:13
[2025-03-13T20:06:13.616+0000] {subprocess.py:93} INFO - [0m20:06:13  Concurrency: 2 threads (target='dev')
[2025-03-13T20:06:13.617+0000] {subprocess.py:93} INFO - [0m20:06:13
[2025-03-13T20:06:14.790+0000] {subprocess.py:93} INFO - [0m20:06:14  1 of 1 START sql incremental model layer_silver.crm_cust_info .................. [RUN]
[2025-03-13T20:06:16.368+0000] {subprocess.py:93} INFO - [0m20:06:16  1 of 1 OK created sql incremental model layer_silver.crm_cust_info ............. [[32mSUCCESS 1[0m in 1.57s]
[2025-03-13T20:06:16.528+0000] {subprocess.py:93} INFO - [0m20:06:16
[2025-03-13T20:06:16.529+0000] {subprocess.py:93} INFO - [0m20:06:16  Finished running 1 incremental model in 0 hours 0 minutes and 2.91 seconds (2.91s).
[2025-03-13T20:06:16.608+0000] {subprocess.py:93} INFO - [0m20:06:16
[2025-03-13T20:06:16.609+0000] {subprocess.py:93} INFO - [0m20:06:16  [32mCompleted successfully[0m
[2025-03-13T20:06:16.610+0000] {subprocess.py:93} INFO - [0m20:06:16
[2025-03-13T20:06:16.610+0000] {subprocess.py:93} INFO - [0m20:06:16  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-03-13T20:06:17.958+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-13T20:06:17.959+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-13T20:06:18.001+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=silver_layer.crm_cust_info, execution_date=20250313T194500, start_date=20250313T200603, end_date=20250313T200618
[2025-03-13T20:06:18.041+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-13T20:06:18.074+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T20:06:18.076+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
