[2025-03-10T18:50:34.895+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-10T18:50:34.919+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.ingest_erp_data manual__2025-03-10T18:50:29.370090+00:00 [queued]>
[2025-03-10T18:50:34.929+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.ingest_erp_data manual__2025-03-10T18:50:29.370090+00:00 [queued]>
[2025-03-10T18:50:34.930+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-10T18:50:34.946+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ingest_erp_data> on 2025-03-10 18:50:29.370090+00:00
[2025-03-10T18:50:34.956+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=58) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T18:50:34.958+0000] {standard_task_runner.py:63} INFO - Started process 62 to run task
[2025-03-10T18:50:34.958+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'ingest_erp_data', 'manual__2025-03-10T18:50:29.370090+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpd7ckvrjn']
[2025-03-10T18:50:34.959+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask ingest_erp_data
[2025-03-10T18:50:34.998+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.ingest_erp_data manual__2025-03-10T18:50:29.370090+00:00 [running]> on host e9482cc19388
[2025-03-10T18:50:35.087+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='ingest_erp_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T18:50:29.370090+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T18:50:29.370090+00:00'
[2025-03-10T18:50:35.088+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-10T18:50:35.104+0000] {pipeline.py:77} INFO - ingest erp data 
[2025-03-10T18:50:35.104+0000] {ingest_data.py:28} ERROR - Error ingesting data from CUST_AZ12.csv into erp_cust_az12: 'NoneType' object has no attribute 'execute'
[2025-03-10T18:50:35.104+0000] {ingest_data.py:28} ERROR - Error ingesting data from LOC_A101.csv into erp_loc_a101: 'NoneType' object has no attribute 'execute'
[2025-03-10T18:50:35.104+0000] {ingest_data.py:28} ERROR - Error ingesting data from PX_CAT_G1V2.csv into erp_px_cat_g1v2: 'NoneType' object has no attribute 'execute'
[2025-03-10T18:50:35.105+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-10T18:50:35.105+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-10T18:50:35.115+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=ingest_erp_data, execution_date=20250310T185029, start_date=20250310T185034, end_date=20250310T185035
[2025-03-10T18:50:35.171+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-10T18:50:35.186+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T18:50:35.188+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
