[2025-03-13T20:15:35.456+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-13T20:15:35.514+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.test_validating_data_silver_layer.crm_prd_info scheduled__2025-03-13T20:00:00+00:00 [queued]>
[2025-03-13T20:15:35.532+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.test_validating_data_silver_layer.crm_prd_info scheduled__2025-03-13T20:00:00+00:00 [queued]>
[2025-03-13T20:15:35.533+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-13T20:15:35.563+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): test_validating_data_silver_layer.crm_prd_info> on 2025-03-13 20:00:00+00:00
[2025-03-13T20:15:35.582+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=845) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T20:15:35.585+0000] {standard_task_runner.py:63} INFO - Started process 861 to run task
[2025-03-13T20:15:35.585+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'test_validating_data_silver_layer.crm_prd_info', 'scheduled__2025-03-13T20:00:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpho0vegwb']
[2025-03-13T20:15:35.589+0000] {standard_task_runner.py:91} INFO - Job 197: Subtask test_validating_data_silver_layer.crm_prd_info
[2025-03-13T20:15:35.671+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.test_validating_data_silver_layer.crm_prd_info scheduled__2025-03-13T20:00:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-13T20:15:35.874+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='test_validating_data_silver_layer.crm_prd_info' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T20:00:00+00:00'
[2025-03-13T20:15:35.876+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-13T20:15:35.899+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-13T20:15:35.899+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --full-refresh --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/sales --models crm_prd_info']
[2025-03-13T20:15:35.930+0000] {subprocess.py:86} INFO - Output:
[2025-03-13T20:15:41.477+0000] {subprocess.py:93} INFO - [0m20:15:41  Running with dbt=1.9.3
[2025-03-13T20:15:42.506+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (19.0.1), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-03-13T20:15:42.506+0000] {subprocess.py:93} INFO -   warn_incompatible_dep(
[2025-03-13T20:15:43.930+0000] {subprocess.py:93} INFO - [0m20:15:43  Registered adapter: snowflake=1.9.2
[2025-03-13T20:15:44.713+0000] {subprocess.py:93} INFO - [0m20:15:44  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-13T20:15:44.713+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-13T20:15:44.714+0000] {subprocess.py:93} INFO - - models.sales.Gold_layer
[2025-03-13T20:15:44.953+0000] {subprocess.py:93} INFO - [0m20:15:44  Found 6 models, 35 data tests, 6 sources, 855 macros
[2025-03-13T20:15:44.957+0000] {subprocess.py:93} INFO - [0m20:15:44
[2025-03-13T20:15:44.958+0000] {subprocess.py:93} INFO - [0m20:15:44  Concurrency: 2 threads (target='dev')
[2025-03-13T20:15:44.958+0000] {subprocess.py:93} INFO - [0m20:15:44
[2025-03-13T20:15:45.958+0000] {subprocess.py:93} INFO - [0m20:15:45  1 of 1 START sql incremental model layer_silver.crm_prd_info ................... [RUN]
[2025-03-13T20:15:46.853+0000] {subprocess.py:93} INFO - [0m20:15:46  1 of 1 OK created sql incremental model layer_silver.crm_prd_info .............. [[32mSUCCESS 1[0m in 0.89s]
[2025-03-13T20:15:47.010+0000] {subprocess.py:93} INFO - [0m20:15:47
[2025-03-13T20:15:47.010+0000] {subprocess.py:93} INFO - [0m20:15:47  Finished running 1 incremental model in 0 hours 0 minutes and 2.05 seconds (2.05s).
[2025-03-13T20:15:47.089+0000] {subprocess.py:93} INFO - [0m20:15:47
[2025-03-13T20:15:47.089+0000] {subprocess.py:93} INFO - [0m20:15:47  [32mCompleted successfully[0m
[2025-03-13T20:15:47.090+0000] {subprocess.py:93} INFO - [0m20:15:47
[2025-03-13T20:15:47.091+0000] {subprocess.py:93} INFO - [0m20:15:47  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-03-13T20:15:48.460+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-13T20:15:48.461+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-13T20:15:48.488+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=test_validating_data_silver_layer.crm_prd_info, execution_date=20250313T200000, start_date=20250313T201535, end_date=20250313T201548
[2025-03-13T20:15:48.531+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-13T20:15:48.549+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T20:15:48.551+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
